name: CI - Playwright & Cucumber Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tags:
        description: 'Filter tests by tag (e.g. @ui or @api)'
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Determine tags for test run
        id: determine-tags
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.tags }}" ]; then
            echo "tags=${{ github.event.inputs.tags }}" >> $GITHUB_OUTPUT
          else
            echo "tags=@ui or @api" >> $GITHUB_OUTPUT
          fi

      - name: Run Cucumber (UI & API) tests
        run: npm run test -- --tags "${{ steps.determine-tags.outputs.tags }}"
        env:
          TAGS: ${{ steps.determine-tags.outputs.tags }}

      - name: Archive test-results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          retention-days: 7